In [1]:
import nba_api.stats.endpoints
import requests
import json
import pandas as pd
import nba_api

In [2]:
import nba_api.stats.endpoints
from nba_api.library.http import NBAHTTP
import time

NBAHTTP.headers = {
    "Host": "stats.nba.com",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Referer": "https://www.nba.com/",
    "Origin": "https://www.nba.com",
    "Connection": "keep-alive",
}

time.sleep(1)

wolves_player_logs = nba_api.stats.endpoints.PlayerGameLogs(
    season_nullable='2025-26',
    team_id_nullable='1610612750'
).get_data_frames()[0]

wolves_player_logs

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT
0,2025-26,1630245,Ayo Dosunmu,Ayo,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,63,85,26,34,54,4,45,1,27:10,1
1,2025-26,203497,Rudy Gobert,Rudy,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,162,105,18,110,1,4,109,1,28:46,1
2,2025-26,203944,Julius Randle,Julius,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,63,105,129,86,54,4,109,1,27:02,1
3,2025-26,1630183,Jaden McDaniels,Jaden,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,386,184,158,268,54,4,241,1,26:17,1
4,2025-26,1630538,Bones Hyland,Bones,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,386,156,12,386,54,4,291,1,24:56,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,2025-26,204060,Joe Ingles,Joe,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,606,370,645,54,4,619,1,16:10,1
852,2025-26,1642389,Zyon Pullin,Zyon,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,659,525,744,54,4,719,1,10:19,1
853,2025-26,1631262,Jules Bernard,Jules,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,739,553,763,54,4,769,1,4:10,1
854,2025-26,1641803,Tristen Newton,Tristen,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,659,370,782,54,4,769,1,3:08,1
855,2025-26,1628993,Alize Johnson,Alize,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,739,370,820,54,4,800,1,7:32,1

In [3]:
pip show nba_api

Name: nba_api
Version: 1.11.4
Summary: An API Client package to access the APIs for NBA.com
Home-page:
Author: Swar Patel
Author-email: <swar.m.patel@gmail.com>
License: MIT
Location: /Users/jackborman/Desktop/PycharmProjects/NBA/venv311/lib/python3.11/site-packages
Requires: numpy, pandas, requests
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [4]:
wolves_player_logs = nba_api.stats.endpoints.PlayerGameLogs(season_nullable='2025-26',team_id_nullable='1610612750').get_data_frames()[0]

wolves_player_logs

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT
0,2025-26,1630245,Ayo Dosunmu,Ayo,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,63,85,26,34,54,4,45,1,27:10,1
1,2025-26,203497,Rudy Gobert,Rudy,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,162,105,18,110,1,4,109,1,28:46,1
2,2025-26,203944,Julius Randle,Julius,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,63,105,129,86,54,4,109,1,27:02,1
3,2025-26,1630183,Jaden McDaniels,Jaden,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,386,184,158,268,54,4,241,1,26:17,1
4,2025-26,1630538,Bones Hyland,Bones,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,386,156,12,386,54,4,291,1,24:56,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851,2025-26,204060,Joe Ingles,Joe,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,606,370,645,54,4,619,1,16:10,1
852,2025-26,1642389,Zyon Pullin,Zyon,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,659,525,744,54,4,719,1,10:19,1
853,2025-26,1631262,Jules Bernard,Jules,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,739,553,763,54,4,769,1,4:10,1
854,2025-26,1641803,Tristen Newton,Tristen,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,659,370,782,54,4,769,1,3:08,1
855,2025-26,1628993,Alize Johnson,Alize,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,739,370,820,54,4,800,1,7:32,1

In [5]:
wolves_player_logs[wolves_player_logs['PLAYER_NAME'] == 'Donte DiVincenzo']

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,...,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG,MIN_SEC,TEAM_COUNT
5,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022501004,2026-03-18T00:00:00,MIN vs. UTA,...,248,395,118,339,54,4,329,1,25:48,1
20,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022500996,2026-03-17T00:00:00,MIN vs. PHX,...,386,739,349,575,54,4,619,1,27:50,1
23,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022500976,2026-03-15T00:00:00,MIN @ OKC,...,386,204,674,303,54,4,220,1,29:39,1
39,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022500966,2026-03-13T00:00:00,MIN @ GSW,...,103,464,158,447,54,4,453,1,27:43,1
49,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022500952,2026-03-11T00:00:00,MIN @ LAC,...,162,493,762,519,54,4,487,1,24:39,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0022500089,2025-10-22T00:00:00,MIN @ POR,...,581,464,572,400,54,4,367,1,20:22,1
788,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0012500064,2025-10-16T00:00:00,MIN @ CHI,...,581,395,614,580,54,4,517,1,18:23,1
811,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0012500039,2025-10-09T00:00:00,MIN @ NYK,...,581,606,174,409,54,4,438,1,23:37,1
834,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0012500036,2025-10-07T00:00:00,MIN vs. IND,...,581,606,415,649,54,4,595,1,8:56,1
841,2025-26,1628978,Donte DiVincenzo,Donte,1610612750,MIN,Minnesota Timberwolves,0012500028,2025-10-04T00:00:00,MIN @ DEN,...,581,433,137,351,54,4,381,1,12:00,1

In [6]:
# Filter for Donte DiVincenzo and Jaden McDaniels
target_players = ['Donte DiVincenzo', 'Jaden McDaniels']
player_filtered = wolves_player_logs[wolves_player_logs['PLAYER_NAME'].isin(target_players)].copy()

# Group by game and sum their combined points
combined_pts = player_filtered.groupby('GAME_ID').agg({
    'PTS': 'sum',
    'GAME_DATE': 'first',
    'MATCHUP': 'first',
    'WL': 'first'  # Win/Loss column if available
}).reset_index()

combined_pts.columns = ['GAME_ID', 'COMBINED_PTS', 'GAME_DATE', 'MATCHUP', 'WL']

# Filter for games where combined PTS >= 30
games_30_plus = combined_pts[combined_pts['COMBINED_PTS'] >= 30].copy()

print(f"Games where Donte DiVincenzo and Jaden McDaniels combined for 30+ points: {len(games_30_plus)}")
print(f"\nGames breakdown:")
games_30_plus.sort_values('COMBINED_PTS', ascending=False).reset_index(drop=True)

Games where Donte DiVincenzo and Jaden McDaniels combined for 30+ points: 26

Games breakdown:

       GAME_ID  COMBINED_PTS            GAME_DATE      MATCHUP WL
0   0022500714            50  2026-02-02T00:00:00    MIN @ MEM  L
1   0022500530            48  2026-01-08T00:00:00  MIN vs. CLE  W
2   0022500841            48  2026-02-24T00:00:00    MIN @ POR  W
3   0022500156            47  2025-11-03T00:00:00    MIN @ BKN  W
4   0022500136            44  2025-10-29T00:00:00  MIN vs. LAL  L
5   0022501220            39  2025-12-14T00:00:00  MIN vs. SAC  W
6   0022501215            38  2025-12-12T00:00:00    MIN @ GSW  W
7   0022500871            37  2026-03-01T00:00:00    MIN @ DEN  W
8   0022500008            37  2025-10-27T00:00:00  MIN vs. DEN  L
9   0022500727            34  2026-02-04T00:00:00    MIN @ TOR  W
10  0022500598            34  2026-01-17T00:00:00    MIN @ SAS  L
11  0022500175            34  2025-11-05T00:00:00    MIN @ NYK  L
12  0022500044            33  2025-11-14T00:00:00  MIN vs. SAC  W
13  0022500616            33  2026-01-20T00:00:00    MIN @ UTA  L
14  0022500355            32  2025-12-06T00:00:00  MIN vs. LAC  W
15  0022500143            32  2025-11-01T00:00:00    MIN @ CHA  W
16  0022500321            32  2025-12-02T00:00:00    MIN @ NOP  W
17  0022500686            32  2026-01-29T00:00:00  MIN vs. OKC  W
18  0022500368            32  2025-12-17T00:00:00  MIN vs. MEM  L
19  0022500700            31  2026-01-31T00:00:00    MIN @ MEM  W
20  0022500306            31  2025-11-30T00:00:00  MIN vs. SAS  W
21  0022500513            31  2026-01-06T00:00:00  MIN vs. MIA  W
22  0022500552            31  2026-01-11T00:00:00  MIN vs. SAS  W
23  0022500824            30  2026-02-22T00:00:00  MIN vs. PHI  L
24  0022500205            30  2025-11-10T00:00:00    MIN @ UTA  W
25  0022500857            30  2026-02-26T00:00:00    MIN @ LAC  W

In [7]:
# Calculate win-loss record
# Check if WL column exists, if not parse from MATCHUP or other columns
if 'WL' in games_30_plus.columns and games_30_plus['WL'].notna().any():
    wins = (games_30_plus['WL'] == 'W').sum()
    losses = (games_30_plus['WL'] == 'L').sum()
else:
    # Try to parse from MATCHUP - if MIN is first, it's a home game
    # We'll need to check actual game results - let's check what columns are available
    print("WL column not found. Checking available columns...")
    print(games_30_plus.columns.tolist())
    # For now, we'll need to get win/loss from another source
    # Let's check if we can get it from the original dataframe
    game_results = wolves_player_logs.groupby('GAME_ID').agg({
        'WL': 'first'
    }).reset_index()
    
    games_30_plus = games_30_plus.merge(game_results, on='GAME_ID', how='left', suffixes=('', '_from_logs'))
    
    if 'WL_from_logs' in games_30_plus.columns:
        games_30_plus['WL'] = games_30_plus['WL_from_logs']
        wins = (games_30_plus['WL'] == 'W').sum()
        losses = (games_30_plus['WL'] == 'L').sum()
    else:
        wins = 0
        losses = 0
        print("Could not determine win/loss record from available data")

if wins + losses > 0:
    win_pct = wins / (wins + losses)
    print(f"\nTimberwolves Record when DiVincenzo + McDaniels combine for 30+ points:")
    print(f"Wins: {wins}")
    print(f"Losses: {losses}")
    print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
    
    # Show the games
    print(f"\nGame Details:")
    display_cols = ['GAME_DATE', 'MATCHUP', 'COMBINED_PTS', 'WL']
    display_cols = [col for col in display_cols if col in games_30_plus.columns]
    print(games_30_plus[display_cols].sort_values('GAME_DATE', ascending=False))
else:
    print("No games found or unable to determine win/loss record")

Timberwolves Record when DiVincenzo + McDaniels combine for 30+ points:
Wins: 18
Losses: 8
Win Percentage: 0.692 (69.2%)

Game Details:
              GAME_DATE      MATCHUP  COMBINED_PTS WL
62  2026-03-01T00:00:00    MIN @ DEN            37  W
61  2026-02-26T00:00:00    MIN @ LAC            30  W
60  2026-02-24T00:00:00    MIN @ POR            48  W
59  2026-02-22T00:00:00  MIN vs. PHI            30  L
53  2026-02-04T00:00:00    MIN @ TOR            34  W
52  2026-02-02T00:00:00    MIN @ MEM            50  L
51  2026-01-31T00:00:00    MIN @ MEM            31  W
50  2026-01-29T00:00:00  MIN vs. OKC            32  W
45  2026-01-20T00:00:00    MIN @ UTA            33  L
44  2026-01-17T00:00:00    MIN @ SAS            34  L
41  2026-01-11T00:00:00  MIN vs. SAS            31  W
39  2026-01-08T00:00:00  MIN vs. CLE            48  W
38  2026-01-06T00:00:00  MIN vs. MIA            31  W
29  2025-12-17T00:00:00  MIN vs. MEM            32  L
73  2025-12-14T00:00:00  MIN vs. SAC            39  W
72  2025-12-12T00:00:00    MIN @ GSW            38  W
27  2025-12-06T00:00:00  MIN vs. LAC            32  W
25  2025-12-02T00:00:00    MIN @ NOP            32  W
24  2025-11-30T00:00:00  MIN vs. SAS            31  W
8   2025-11-14T00:00:00  MIN vs. SAC            33  W
18  2025-11-10T00:00:00    MIN @ UTA            30  W
16  2025-11-05T00:00:00    MIN @ NYK            34  L
15  2025-11-03T00:00:00    MIN @ BKN            47  W
14  2025-11-01T00:00:00    MIN @ CHA            32  W
13  2025-10-29T00:00:00  MIN vs. LAL            44  L
4   2025-10-27T00:00:00  MIN vs. DEN            37  L

In [8]:
# Starting five: DiVincenzo, McDaniels, Anthony Edwards, Julius Randle, Rudy Gobert
starting_five = ['Donte DiVincenzo', 'Jaden McDaniels', 'Anthony Edwards', 'Julius Randle', 'Rudy Gobert']
# starting_five = ['Naz Reid', 'Bones Hyland']

# Filter for starting five players
starting_five_logs = wolves_player_logs[wolves_player_logs['PLAYER_NAME'].isin(starting_five)].copy()

# Create a pivot table: games as rows, players as columns, PTS as values
pivot_pts = starting_five_logs.pivot_table(
    index='GAME_ID',
    columns='PLAYER_NAME',
    values='PTS',
    aggfunc='first'
).reset_index()

# Get game metadata
game_metadata = starting_five_logs.groupby('GAME_ID').agg({
    'GAME_DATE': 'first',
    'MATCHUP': 'first',
    'WL': 'first'
}).reset_index()

# Merge with pivot table
starting_five_games = pivot_pts.merge(game_metadata, on='GAME_ID', how='left')

# Check if all five players scored at least 10 points in each game
# First, ensure all five player columns exist (fill missing with 0)
for player in starting_five:
    if player not in starting_five_games.columns:
        starting_five_games[player] = 0

# Filter for games where all five scored at least 10 points
all_10_plus = starting_five_games[
    # (starting_five_games['Naz Reid'] >= 10) &
    (starting_five_games['Jaden McDaniels'] >= 10) &
    (starting_five_games['Anthony Edwards'] >= 10) &
    (starting_five_games['Julius Randle'] >= 10) &
    (starting_five_games['Donte DiVincenzo'] >= 10) &
    (starting_five_games['Rudy Gobert'] >= 10)
].copy()

print(f"Games where all five starters scored 10+ points: {len(all_10_plus)}")
print(f"\nTotal games in dataset: {len(starting_five_games)}")
print(f"Percentage: {len(all_10_plus)/len(starting_five_games)*100:.1f}%")

# Display the games
if len(all_10_plus) > 0:
    display_cols = ['GAME_DATE', 'MATCHUP'] + starting_five + ['WL']
    display_cols = [col for col in display_cols if col in all_10_plus.columns]
    all_10_plus[display_cols].sort_values('GAME_DATE', ascending=False)
else:
    print("\nNo games found where all five starters scored 10+ points")

Games where all five starters scored 10+ points: 13

Total games in dataset: 74
Percentage: 17.6%

In [9]:
# Calculate win-loss record for games where all five starters scored 10+ points
from IPython.display import display

if len(all_10_plus) > 0:
    # Ensure WL column exists
    if 'WL' not in all_10_plus.columns or all_10_plus['WL'].isna().all():
        # Get WL from original dataframe if missing
        game_results = wolves_player_logs.groupby('GAME_ID').agg({
            'WL': 'first'
        }).reset_index()
        all_10_plus = all_10_plus.merge(game_results, on='GAME_ID', how='left', suffixes=('', '_from_logs'))
        if 'WL_from_logs' in all_10_plus.columns:
            all_10_plus['WL'] = all_10_plus['WL_from_logs']
    
    wins = (all_10_plus['WL'] == 'W').sum()
    losses = (all_10_plus['WL'] == 'L').sum()
    
    if wins + losses > 0:
        win_pct = wins / (wins + losses)
        print(f"\nTimberwolves Record when all five starters score 10+ points:")
        print(f"Wins: {wins}")
        print(f"Losses: {losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show detailed breakdown
        print(f"\nGame Details:")
        display_cols = ['GAME_DATE', 'MATCHUP', 
                       'Naz Reid', 'Donte DiVincenzo', 'Jaden McDaniels', 
                       'Anthony Edwards', 'Julius Randle', 'Rudy Gobert', 'WL']
        display_cols = [col for col in display_cols if col in all_10_plus.columns]
        
        # Calculate total points for each game
        all_10_plus_display = all_10_plus[display_cols].copy()
        player_cols = [col for col in starting_five if col in all_10_plus_display.columns]
        if player_cols:
            all_10_plus_display['TOTAL_PTS'] = all_10_plus_display[player_cols].sum(axis=1)
            display_cols = ['GAME_DATE', 'MATCHUP'] + player_cols + ['TOTAL_PTS', 'WL']
            display_cols = [col for col in display_cols if col in all_10_plus_display.columns]
        
        # Display the dataframe (using print like in Cell 4)
        result_df = all_10_plus_display[display_cols].sort_values('GAME_DATE', ascending=False)
        print(result_df)
    else:
        print("Could not determine win/loss record")
else:
    print("No games found where all five starters scored 10+ points")

Timberwolves Record when all five starters score 10+ points:
Wins: 11
Losses: 2
Win Percentage: 0.846 (84.6%)

Game Details:
              GAME_DATE      MATCHUP  Donte DiVincenzo  Jaden McDaniels  \
60  2026-02-24T00:00:00    MIN @ POR              19.0             29.0
56  2026-02-09T00:00:00  MIN vs. ATL              10.0             18.0
53  2026-02-04T00:00:00    MIN @ TOR              15.0             19.0
50  2026-01-29T00:00:00  MIN vs. OKC              11.0             21.0
46  2026-01-22T00:00:00  MIN vs. CHI              11.0             16.0
45  2026-01-20T00:00:00    MIN @ UTA              15.0             18.0
39  2026-01-08T00:00:00  MIN vs. CLE              22.0             26.0
38  2026-01-06T00:00:00  MIN vs. MIA              12.0             19.0
26  2025-12-04T00:00:00    MIN @ NOP              15.0             14.0
25  2025-12-02T00:00:00    MIN @ NOP              15.0             17.0
20  2025-11-17T00:00:00  MIN vs. DAL              14.0             15.0
8   2025-11-14T00:00:00  MIN vs. SAC              20.0             13.0
18  2025-11-10T00:00:00    MIN @ UTA              14.0             16.0

    Anthony Edwards  Julius Randle  Rudy Gobert  TOTAL_PTS WL
60             34.0           13.0         10.0      105.0  W
56             30.0           18.0         18.0       94.0  W
53             30.0           17.0         10.0       91.0  W
50             26.0           13.0         14.0       85.0  W
46             20.0           30.0         10.0       87.0  L
45             38.0           19.0         11.0      101.0  L
39             25.0           28.0         11.0      112.0  W
38             26.0           15.0         13.0       85.0  W
26             11.0           28.0         15.0       83.0  W
25             44.0           16.0         26.0      118.0  W
20             13.0           12.0         15.0       69.0  W
8              30.0           26.0         11.0      100.0  W
18             35.0           27.0         14.0      106.0  W

In [10]:
# Filter for Julius Randle games
randle_logs = wolves_player_logs[wolves_player_logs['PLAYER_NAME'] == 'Julius Randle'].copy()

# Check what column name is used for three-pointers made
# Common names: FG3M, FG3_M, FG3MADE, or similar
three_pt_col = None
for col in ['FG3M', 'FG3_M', 'FG3MADE', 'FG3A_MADE']:
    if col in randle_logs.columns:
        three_pt_col = col
        break

if three_pt_col is None:
    # List available columns to help identify the correct one
    print("Three-pointer column not found. Available columns:")
    print([col for col in randle_logs.columns if '3' in col.upper() or 'THREE' in col.upper()])
    # Try common alternative
    three_pt_col = 'FG3M' if 'FG3M' in randle_logs.columns else None

if three_pt_col:
    # Filter for games where Randle made at least 3 three-pointers
    randle_3plus_3pt = randle_logs[randle_logs[three_pt_col] >= 3].copy()
    
    print(f"Games where Julius Randle made 3+ three-pointers: {len(randle_3plus_3pt)}")
    print(f"\nTotal games played by Randle: {len(randle_logs)}")
    print(f"Percentage: {len(randle_3plus_3pt)/len(randle_logs)*100:.1f}%")
    
    # Calculate win-loss record
    if 'WL' not in randle_3plus_3pt.columns or randle_3plus_3pt['WL'].isna().all():
        # Get WL from original dataframe if missing
        game_results = wolves_player_logs.groupby('GAME_ID').agg({
            'WL': 'first'
        }).reset_index()
        randle_3plus_3pt = randle_3plus_3pt.merge(game_results, on='GAME_ID', how='left', suffixes=('', '_from_logs'))
        if 'WL_from_logs' in randle_3plus_3pt.columns:
            randle_3plus_3pt['WL'] = randle_3plus_3pt['WL_from_logs']
    
    wins = (randle_3plus_3pt['WL'] == 'W').sum()
    losses = (randle_3plus_3pt['WL'] == 'L').sum()
    
    if wins + losses > 0:
        win_pct = wins / (wins + losses)
        print(f"\nTimberwolves Record when Julius Randle makes 3+ three-pointers:")
        print(f"Wins: {wins}")
        print(f"Losses: {losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show the games
        print(f"\nGame Details:")
        display_cols = ['GAME_DATE', 'MATCHUP', 'PTS', three_pt_col, 'WL']
        display_cols = [col for col in display_cols if col in randle_3plus_3pt.columns]
        print(randle_3plus_3pt[display_cols].sort_values('GAME_DATE', ascending=False))
    else:
        print("Could not determine win/loss record")
else:
    print("Could not find three-pointer column in the data")

Games where Julius Randle made 3+ three-pointers: 13

Total games played by Randle: 73
Percentage: 17.8%

Timberwolves Record when Julius Randle makes 3+ three-pointers:
Wins: 7
Losses: 6
Win Percentage: 0.538 (53.8%)

Game Details:
               GAME_DATE      MATCHUP  PTS  FG3M WL
21   2026-03-15T00:00:00    MIN @ OKC   32     3  L
153  2026-02-11T00:00:00  MIN vs. POR   41     3  W
217  2026-01-31T00:00:00    MIN @ MEM   27     4  W
275  2026-01-22T00:00:00  MIN vs. CHI   30     3  L
315  2026-01-13T00:00:00    MIN @ MIL   29     4  W
349  2026-01-08T00:00:00  MIN vs. CLE   28     3  W
395  2025-12-31T00:00:00    MIN @ ATL   19     3  L
555  2025-11-29T00:00:00  MIN vs. BOS   16     3  W
675  2025-11-05T00:00:00    MIN @ NYK   32     3  L
700  2025-11-01T00:00:00    MIN @ CHA   30     3  W
712  2025-10-29T00:00:00  MIN vs. LAL   33     4  L
745  2025-10-24T00:00:00    MIN @ LAL   26     4  L
760  2025-10-22T00:00:00    MIN @ POR   19     3  W

In [11]:
# Filter for Julius Randle games
randle_logs = wolves_player_logs[wolves_player_logs['PLAYER_NAME'] == 'Julius Randle'].copy()

# Check what column name is used for three-pointers made
# Common names: FG3M, FG3_M, FG3MADE, or similar
three_pt_col = None
for col in ['FG3M', 'FG3_M', 'FG3MADE', 'FG3A_MADE']:
    if col in randle_logs.columns:
        three_pt_col = col
        break

if three_pt_col is None:
    # List available columns to help identify the correct one
    print("Three-pointer column not found. Available columns:")
    print([col for col in randle_logs.columns if '3' in col.upper() or 'THREE' in col.upper()])
    # Try common alternative
    three_pt_col = 'FG3M' if 'FG3M' in randle_logs.columns else None

if three_pt_col:
    # Filter for games where Randle made at least 3 three-pointers
    randle_3plus_3pt = randle_logs[randle_logs[three_pt_col] >= 3].copy()
    
    print(f"Games where Julius Randle made 3+ three-pointers: {len(randle_3plus_3pt)}")
    print(f"\nTotal games played by Randle: {len(randle_logs)}")
    print(f"Percentage: {len(randle_3plus_3pt)/len(randle_logs)*100:.1f}%")
    
    # Calculate win-loss record
    if 'WL' not in randle_3plus_3pt.columns or randle_3plus_3pt['WL'].isna().all():
        # Get WL from original dataframe if missing
        game_results = wolves_player_logs.groupby('GAME_ID').agg({
            'WL': 'first'
        }).reset_index()
        randle_3plus_3pt = randle_3plus_3pt.merge(game_results, on='GAME_ID', how='left', suffixes=('', '_from_logs'))
        if 'WL_from_logs' in randle_3plus_3pt.columns:
            randle_3plus_3pt['WL'] = randle_3plus_3pt['WL_from_logs']
    
    wins = (randle_3plus_3pt['WL'] == 'W').sum()
    losses = (randle_3plus_3pt['WL'] == 'L').sum()
    
    if wins + losses > 0:
        win_pct = wins / (wins + losses)
        print(f"\nTimberwolves Record when Julius Randle makes 3+ three-pointers:")
        print(f"Wins: {wins}")
        print(f"Losses: {losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show the games
        print(f"\nGame Details:")
        display_cols = ['GAME_DATE', 'MATCHUP', 'PTS', three_pt_col, 'WL']
        display_cols = [col for col in display_cols if col in randle_3plus_3pt.columns]
        print(randle_3plus_3pt[display_cols].sort_values('GAME_DATE', ascending=False))
    else:
        print("Could not determine win/loss record")
else:
    print("Could not find three-pointer column in the data")

Games where Julius Randle made 3+ three-pointers: 13

Total games played by Randle: 73
Percentage: 17.8%

Timberwolves Record when Julius Randle makes 3+ three-pointers:
Wins: 7
Losses: 6
Win Percentage: 0.538 (53.8%)

Game Details:
               GAME_DATE      MATCHUP  PTS  FG3M WL
21   2026-03-15T00:00:00    MIN @ OKC   32     3  L
153  2026-02-11T00:00:00  MIN vs. POR   41     3  W
217  2026-01-31T00:00:00    MIN @ MEM   27     4  W
275  2026-01-22T00:00:00  MIN vs. CHI   30     3  L
315  2026-01-13T00:00:00    MIN @ MIL   29     4  W
349  2026-01-08T00:00:00  MIN vs. CLE   28     3  W
395  2025-12-31T00:00:00    MIN @ ATL   19     3  L
555  2025-11-29T00:00:00  MIN vs. BOS   16     3  W
675  2025-11-05T00:00:00    MIN @ NYK   32     3  L
700  2025-11-01T00:00:00    MIN @ CHA   30     3  W
712  2025-10-29T00:00:00  MIN vs. LAL   33     4  L
745  2025-10-24T00:00:00    MIN @ LAL   26     4  L
760  2025-10-22T00:00:00    MIN @ POR   19     3  W

In [12]:
# Find games where at least 4 players scored 20+ points
# Group by game and count how many players scored 20+ points in each game
games_with_20_plus = wolves_player_logs[wolves_player_logs['PTS'] >= 20].copy()

# Count how many players scored 20+ in each game
players_20_plus_per_game = games_with_20_plus.groupby('GAME_ID').agg({
    'PLAYER_NAME': 'count',
    'GAME_DATE': 'first',
    'MATCHUP': 'first',
    'WL': 'first'
}).reset_index()

players_20_plus_per_game.columns = ['GAME_ID', 'PLAYERS_20_PLUS', 'GAME_DATE', 'MATCHUP', 'WL']

# Filter for games where at least 4 players scored 20+ points
games_4plus_20pts = players_20_plus_per_game[players_20_plus_per_game['PLAYERS_20_PLUS'] >= 4].copy()

print(f"Games where at least 4 players scored 20+ points: {len(games_4plus_20pts)}")
print(f"\nTotal games in dataset: {len(players_20_plus_per_game)}")
if len(players_20_plus_per_game) > 0:
    print(f"Percentage: {len(games_4plus_20pts)/len(players_20_plus_per_game)*100:.1f}%")

# Display the games
if len(games_4plus_20pts) > 0:
    display(games_4plus_20pts.sort_values('GAME_DATE', ascending=False))
else:
    print("\nNo games found where at least 4 players scored 20+ points")

Games where at least 4 players scored 20+ points: 2

Total games in dataset: 72
Percentage: 2.8%

       GAME_ID  PLAYERS_20_PLUS            GAME_DATE      MATCHUP WL
50  0022500700                4  2026-01-31T00:00:00    MIN @ MEM  W
39  0022500530                4  2026-01-08T00:00:00  MIN vs. CLE  W

In [13]:
# Calculate win-loss record for games where at least 4 players scored 20+ points
from IPython.display import display

if len(games_4plus_20pts) > 0:
    # Ensure WL column exists
    if 'WL' not in games_4plus_20pts.columns or games_4plus_20pts['WL'].isna().all():
        # Get WL from original dataframe if missing
        game_results = wolves_player_logs.groupby('GAME_ID').agg({
            'WL': 'first'
        }).reset_index()
        games_4plus_20pts = games_4plus_20pts.merge(game_results, on='GAME_ID', how='left', suffixes=('', '_from_logs'))
        if 'WL_from_logs' in games_4plus_20pts.columns:
            games_4plus_20pts['WL'] = games_4plus_20pts['WL_from_logs']
    
    wins = (games_4plus_20pts['WL'] == 'W').sum()
    losses = (games_4plus_20pts['WL'] == 'L').sum()
    
    if wins + losses > 0:
        win_pct = wins / (wins + losses)
        print(f"\nTimberwolves Record when at least 4 players score 20+ points:")
        print(f"Wins: {wins}")
        print(f"Losses: {losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show detailed breakdown
        print(f"\nGame Details:")
        display_cols = ['GAME_ID', 'GAME_DATE', 'MATCHUP', 'PLAYERS_20_PLUS', 'WL']
        display_cols = [col for col in display_cols if col in games_4plus_20pts.columns]
        
        # Get player names who scored 20+ for each game
        games_4plus_20pts_display = games_4plus_20pts[display_cols].copy()
        
        # For each game, get the list of players who scored 20+
        player_lists = []
        for game_id in games_4plus_20pts_display['GAME_ID']:
            game_players = games_with_20_plus[games_with_20_plus['GAME_ID'] == game_id]['PLAYER_NAME'].tolist()
            player_lists.append(', '.join(game_players))
        
        games_4plus_20pts_display['PLAYERS'] = player_lists
        
        # Display the dataframe
        result_df = games_4plus_20pts_display.sort_values('GAME_DATE', ascending=False)
        print(result_df)
    else:
        print("Could not determine win/loss record")
else:
    print("No games found where at least 4 players scored 20+ points")

Timberwolves Record when at least 4 players score 20+ points:
Wins: 2
Losses: 0
Win Percentage: 1.000 (100.0%)

Game Details:
       GAME_ID            GAME_DATE      MATCHUP  PLAYERS_20_PLUS WL  \
50  0022500700  2026-01-31T00:00:00    MIN @ MEM                4  W
39  0022500530  2026-01-08T00:00:00  MIN vs. CLE                4  W

                                              PLAYERS
50  Julius Randle, Naz Reid, Anthony Edwards, Jade...
39  Julius Randle, Anthony Edwards, Jaden McDaniel...

In [14]:
# Find games where at least 6 players scored 10+ points (regular season only)
# GAME_ID position [2]: '2' = regular season, '4' = playoffs
wolves_rs = wolves_player_logs[wolves_player_logs['GAME_ID'].astype(str).str[2] == '2']
games_with_10_plus = wolves_rs[wolves_rs['PTS'] >= 10].copy()

# Count how many players scored 10+ in each game
players_10_plus_per_game = games_with_10_plus.groupby('GAME_ID').agg({
    'PLAYER_NAME': 'count',
    'GAME_DATE': 'first',
    'MATCHUP': 'first',
    'WL': 'first'
}).reset_index()

players_10_plus_per_game.columns = ['GAME_ID', 'PLAYERS_10_PLUS', 'GAME_DATE', 'MATCHUP', 'WL']

# Filter for games where at least 6 players scored 10+ points
games_6plus_10pts = players_10_plus_per_game[players_10_plus_per_game['PLAYERS_10_PLUS'] >= 6].copy()

print(f"Games where at least 6 players scored 10+ points: {len(games_6plus_10pts)}")

# Calculate win-loss record
if len(games_6plus_10pts) > 0:
    wins = (games_6plus_10pts['WL'] == 'W').sum()
    losses = (games_6plus_10pts['WL'] == 'L').sum()
    total = wins + losses
    
    if total > 0:
        win_pct = wins / total
        print(f"\nTimberwolves Record when at least 6 players score 10+ points:")
        print(f"Record: {wins}-{losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show game details with players who scored 10+
        print(f"\nGame Details:")
        games_6plus_10pts_display = games_6plus_10pts.copy()
        
        player_lists = []
        for game_id in games_6plus_10pts_display['GAME_ID']:
            game_players = games_with_10_plus[games_with_10_plus['GAME_ID'] == game_id][['PLAYER_NAME', 'PTS']].copy()
            game_players = game_players.sort_values('PTS', ascending=False)
            player_strs = [f"{row['PLAYER_NAME']} ({int(row['PTS'])})" for _, row in game_players.iterrows()]
            player_lists.append(', '.join(player_strs))
        
        games_6plus_10pts_display['PLAYERS'] = player_lists
        
        result_df = games_6plus_10pts_display[['GAME_DATE', 'MATCHUP', 'WL', 'PLAYERS_10_PLUS', 'PLAYERS']].sort_values('GAME_DATE', ascending=False)
        display(result_df)
    else:
        print("Could not determine win/loss record")
else:
    print("No games found where at least 6 players scored 10+ points")

Games where at least 6 players scored 10+ points: 28

Timberwolves Record when at least 6 players score 10+ points:
Record: 21-7
Win Percentage: 0.750 (75.0%)

Game Details:

,GAME_DATE,MATCHUP,WL,PLAYERS_10_PLUS,PLAYERS
64,2026-03-13T00:00:00,MIN @ GSW,W,7,"Anthony Edwards (42), Rudy Gobert (18), Jaden ..."
63,2026-03-11T00:00:00,MIN @ LAC,L,6,"Anthony Edwards (36), Naz Reid (18), Julius Ra..."
62,2026-03-10T00:00:00,MIN @ LAL,L,6,"Anthony Edwards (14), Julius Randle (14), Naz ..."
60,2026-03-05T00:00:00,MIN vs. TOR,W,6,"Anthony Edwards (22), Rudy Gobert (18), Julius..."
58,2026-03-01T00:00:00,MIN @ DEN,W,6,"Anthony Edwards (21), Jaden McDaniels (20), Bo..."
53,2026-02-11T00:00:00,MIN vs. POR,W,6,"Julius Randle (41), Jaden McDaniels (21), Rudy..."
52,2026-02-09T00:00:00,MIN vs. ATL,W,7,"Anthony Edwards (30), Ayo Dosunmu (21), Julius..."
49,2026-02-04T00:00:00,MIN @ TOR,W,7,"Anthony Edwards (30), Bones Hyland (20), Jaden..."
46,2026-01-29T00:00:00,MIN vs. OKC,W,6,"Anthony Edwards (26), Jaden McDaniels (21), Na..."
44,2026-01-26T00:00:00,MIN vs. GSW,W,6,"Julius Randle (18), Bones Hyland (17), Rudy Go..."
42,2026-01-22T00:00:00,MIN vs. CHI,L,6,"Julius Randle (30), Naz Reid (20), Anthony Edw..."
41,2026-01-20T00:00:00,MIN @ UTA,L,6,"Anthony Edwards (38), Julius Randle (19), Jade..."
38,2026-01-13T00:00:00,MIN @ MIL,W,6,"Julius Randle (29), Bones Hyland (23), Naz Rei..."
37,2026-01-11T00:00:00,MIN vs. SAS,W,6,"Anthony Edwards (23), Donte DiVincenzo (19), N..."
36,2026-01-10T00:00:00,MIN @ CLE,L,6,"Naz Reid (25), Anthony Edwards (25), Julius Ra..."
34,2026-01-06T00:00:00,MIN vs. MIA,W,6,"Anthony Edwards (26), Jaden McDaniels (19), Ju..."
30,2025-12-29T00:00:00,MIN @ CHI,W,6,"Naz Reid (33), Anthony Edwards (23), Julius Ra..."
27,2025-12-21T00:00:00,MIN vs. MIL,W,6,"Anthony Edwards (24), Donte DiVincenzo (18), J..."
26,2025-12-19T00:00:00,MIN vs. OKC,W,6,"Anthony Edwards (26), Julius Randle (19), Naz ..."
25,2025-12-17T00:00:00,MIN vs. MEM,L,6,"Julius Randle (21), Donte DiVincenzo (19), Rud..."
22,2025-12-04T00:00:00,MIN @ NOP,W,7,"Julius Randle (28), Naz Reid (19), Rudy Gobert..."
21,2025-12-02T00:00:00,MIN @ NOP,W,6,"Anthony Edwards (44), Rudy Gobert (26), Naz Re..."
19,2025-11-29T00:00:00,MIN vs. BOS,W,6,"Anthony Edwards (39), Julius Randle (16), Dont..."
6,2025-11-26T00:00:00,MIN @ OKC,L,6,"Anthony Edwards (31), Terrence Shannon Jr. (18..."
16,2025-11-17T00:00:00,MIN vs. DAL,W,6,"Naz Reid (22), Rudy Gobert (15), Jaden McDanie..."
4,2025-11-14T00:00:00,MIN vs. SAC,W,6,"Anthony Edwards (30), Julius Randle (26), Dont..."
13,2025-11-09T00:00:00,MIN @ SAC,W,7,"Anthony Edwards (26), Jaden McDaniels (21), Ru..."
10,2025-11-01T00:00:00,MIN @ CHA,W,6,"Julius Randle (30), Donte DiVincenzo (18), Naz..."

In [15]:
# Filter for games where at least 7 players scored 10+ points
games_7plus_10pts = players_10_plus_per_game[players_10_plus_per_game['PLAYERS_10_PLUS'] >= 7].copy()

print(f"Games where at least 7 players scored 10+ points: {len(games_7plus_10pts)}")

# Calculate win-loss record
if len(games_7plus_10pts) > 0:
    wins = (games_7plus_10pts['WL'] == 'W').sum()
    losses = (games_7plus_10pts['WL'] == 'L').sum()
    total = wins + losses
    
    if total > 0:
        win_pct = wins / total
        print(f"\nTimberwolves Record when at least 7 players score 10+ points:")
        print(f"Record: {wins}-{losses}")
        print(f"Win Percentage: {win_pct:.3f} ({win_pct*100:.1f}%)")
        
        # Show game details with players who scored 10+
        print(f"\nGame Details:")
        games_7plus_10pts_display = games_7plus_10pts.copy()
        
        player_lists = []
        for game_id in games_7plus_10pts_display['GAME_ID']:
            game_players = games_with_10_plus[games_with_10_plus['GAME_ID'] == game_id][['PLAYER_NAME', 'PTS']].copy()
            game_players = game_players.sort_values('PTS', ascending=False)
            player_strs = [f"{row['PLAYER_NAME']} ({int(row['PTS'])})" for _, row in game_players.iterrows()]
            player_lists.append(', '.join(player_strs))
        
        games_7plus_10pts_display['PLAYERS'] = player_lists
        
        result_df = games_7plus_10pts_display[['GAME_DATE', 'MATCHUP', 'WL', 'PLAYERS_10_PLUS', 'PLAYERS']].sort_values('GAME_DATE', ascending=False)
        display(result_df)
    else:
        print("Could not determine win/loss record")
else:
    print("No games found where at least 7 players scored 10+ points")

Games where at least 7 players scored 10+ points: 5

Timberwolves Record when at least 7 players score 10+ points:
Record: 5-0
Win Percentage: 1.000 (100.0%)

Game Details:

,GAME_DATE,MATCHUP,WL,PLAYERS_10_PLUS,PLAYERS
64,2026-03-13T00:00:00,MIN @ GSW,W,7,"Anthony Edwards (42), Rudy Gobert (18), Jaden ..."
52,2026-02-09T00:00:00,MIN vs. ATL,W,7,"Anthony Edwards (30), Ayo Dosunmu (21), Julius..."
49,2026-02-04T00:00:00,MIN @ TOR,W,7,"Anthony Edwards (30), Bones Hyland (20), Jaden..."
22,2025-12-04T00:00:00,MIN @ NOP,W,7,"Julius Randle (28), Naz Reid (19), Rudy Gobert..."
13,2025-11-09T00:00:00,MIN @ SAC,W,7,"Anthony Edwards (26), Jaden McDaniels (21), Ru..."